/** ABI for ArcadeTwitterEscrow. Holds Clanker LP fees attributed to a Twitter
 *  @handle and releases them on a backend-signed EIP-712 claim. */
export const TWITTER_ESCROW_ABI = [
  {
    type: "function",
    name: "LOCKER",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "TRUSTED_SIGNER",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "DOMAIN_SEPARATOR",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "bytes32" }],
  },
  {
    type: "function",
    name: "claimed",
    stateMutability: "view",
    inputs: [
      { name: "positionId", type: "uint256" },
      { name: "slotIndex", type: "uint256" },
    ],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "nonceUsed",
    stateMutability: "view",
    inputs: [{ name: "nonce", type: "bytes32" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "claim",
    stateMutability: "nonpayable",
    inputs: [
      { name: "positionId", type: "uint256" },
      { name: "slotIndex", type: "uint256" },
      { name: "recipient", type: "address" },
      { name: "pairedToken", type: "address" },
      { name: "pairedAmount", type: "uint256" },
      { name: "clankerToken", type: "address" },
      { name: "clankerAmount", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "nonce", type: "bytes32" },
      { name: "signature", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "authorize",
    stateMutability: "nonpayable",
    inputs: [
      { name: "positionId", type: "uint256" },
      { name: "slotIndex", type: "uint256" },
      { name: "recipient", type: "address" },
      { name: "pairedToken", type: "address" },
      { name: "pairedAmount", type: "uint256" },
      { name: "clankerToken", type: "address" },
      { name: "clankerAmount", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "nonce", type: "bytes32" },
      { name: "signature", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "claimByTwitter",
    stateMutability: "nonpayable",
    inputs: [{ name: "nonce", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "pendingClaims",
    stateMutability: "view",
    inputs: [{ name: "nonce", type: "bytes32" }],
    outputs: [
      { name: "recipient", type: "address" },
      { name: "pairedToken", type: "address" },
      { name: "pairedAmount", type: "uint256" },
      { name: "clankerToken", type: "address" },
      { name: "clankerAmount", type: "uint256" },
      { name: "positionId", type: "uint256" },
      { name: "slotIndex", type: "uint256" },
      { name: "executeAfter", type: "uint64" },
      { name: "deadline", type: "uint64" },
      { name: "consumed", type: "bool" },
      { name: "vetoed", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "claimTimelock",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint64" }],
  },
  {
    type: "function",
    name: "veto",
    stateMutability: "nonpayable",
    inputs: [{ name: "nonce", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setClaimTimelock",
    stateMutability: "nonpayable",
    inputs: [{ name: "newTimelock", type: "uint64" }],
    outputs: [],
  },
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  // True iff (positionId, slotIndex) has an in-flight pending authorization.
  // Set by `authorize`, cleared by `claim` / `claimByTwitter` / `veto`. Used
  // to prevent zombie pendingClaims.
  {
    type: "function",
    name: "hasPending",
    stateMutability: "view",
    inputs: [
      { name: "positionId", type: "uint256" },
      { name: "slotIndex", type: "uint256" },
    ],
    outputs: [{ type: "bool" }],
  },
  // Owner-only escape hatch to sweep stuck or vetoed tokens.
  {
    type: "function",
    name: "rescue",
    stateMutability: "nonpayable",
    inputs: [
      { name: "token", type: "address" },
      { name: "to", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "event",
    name: "Claimed",
    inputs: [
      { name: "positionId", type: "uint256", indexed: true },
      { name: "slotIndex", type: "uint256", indexed: true },
      { name: "recipient", type: "address", indexed: true },
      { name: "pairedToken", type: "address", indexed: false },
      { name: "pairedAmount", type: "uint256", indexed: false },
      { name: "clankerToken", type: "address", indexed: false },
      { name: "clankerAmount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Rescued",
    inputs: [
      { name: "token", type: "address", indexed: true },
      { name: "to", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
] as const;
